export const playgroundToonComponentKeys = [
  "text",
  "heading",
  "separator",
  "card",
  "form",
  "field",
  "button",
  "confirm",
  "list",
  "item",
  "badge",
  "alert",
  "table",
  "empty",
  "tabs",
  "tab",
  "accordion",
  "section",
  "dialog",
  "sheet",
  "popover",
  "tooltip",
  "progress",
  "loading",
  "toast",
  "breadcrumb",
  "crumb",
  "pagination",
  "menu",
  "command",
  "action",
  "chart",
  "series",
  "point",
] as const;

export type PlaygroundToonComponentKey = (typeof playgroundToonComponentKeys)[number];
